package PreservaView;
import java.awt.Color;
import java.awt.Container;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Patrik & Per
 */
public class MainWindowUI extends javax.swing.JFrame {
    ArrayList domannamnArray = new ArrayList<>();
    DefaultListModel listModel = new DefaultListModel();
    DefaultListModel listInsamling = new DefaultListModel();
    DefaultTableModel tableModel = new DefaultTableModel();
    InsamlingEntity insamling = new InsamlingEntity();
    /**
     * Creates new form MainWindow
     */
    public MainWindowUI() throws SQLException{
        //Auto-generated code
        initComponents();
        //Sets background and table-attributes
        initGUIMainFrame();
        //Sets predefined values in insamling-tab
        initGUIregInsamling();    
        //Gets data from DB to JTable
        //showTable();
    }
    private void initGUIMainFrame() {
        try {
            Container a = this.getContentPane();
            a.setBackground(Color.white);
            setTableAttributes();
            JTabbedPane tabp = new JTabbedPane();
            tabp.setBackground(Color.red);
            updateNameCmb();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindowUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbInsamlingsprofil = new javax.swing.JComboBox();
        cmbBoxStatus = new javax.swing.JComboBox();
        txtInsamlingsdoman = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaKommentar = new javax.swing.JTextArea();
        txtDate = new javax.swing.JTextField();
        lblSkapaInsProfil = new javax.swing.JLabel();
        cmbKundnamn = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        btnCreateInsamling = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JlistDomanNamn = new javax.swing.JList();
        jLabel20 = new javax.swing.JLabel();
        lblAddDoman = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        createNewCustomerBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        customerCityTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        customerEmailTxtField = new javax.swing.JTextField();
        customerPhoneNumberTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        customerNameTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        customerStreetTxtField = new javax.swing.JTextField();
        customerPostCodeTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1051, 632));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PreservaView/header.jpg"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(148, 194, 29));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setBackground(new java.awt.Color(124, 126, 44));
        jButton7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Samtliga");

        jButton8.setBackground(new java.awt.Color(148, 176, 35));
        jButton8.setText("Pågående");

        jButton9.setBackground(new java.awt.Color(148, 176, 35));
        jButton9.setText("Ej startade");

        jButton10.setBackground(new java.awt.Color(148, 176, 35));
        jButton10.setText("Levererade");

        jLabel3.setText("90");

        jLabel4.setText("10");

        jLabel5.setText("20");

        jLabel6.setText("60");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jLabel6))
                .addGap(0, 204, Short.MAX_VALUE))
        );

        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 176, 35), 2, true));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insamlingsnummer", "Kundnamn", "Startdatum", "Domän", "Status", "Kommentar", "URL", "Rapport", "Starta insamling"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insamlingar      ", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 203, 8)));
        jPanel7.setForeground(new java.awt.Color(129, 203, 8));
        jPanel7.setPreferredSize(new java.awt.Dimension(876, 353));

        jLabel11.setText("Kommentar:");

        jLabel12.setText("Status:");

        jLabel13.setText("Insamlingsprofil:");

        jLabel14.setText("Insamlingsdomän:");

        jLabel15.setText("StartDatum:");

        jLabel16.setText("Kund:");

        jLabel17.setText("InsamlingsID:");

        cmbInsamlingsprofil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Profil1", "Profil2", "Ny Profil" }));

        cmbBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ej startad", "Pågår", "Klar", "Levererad" }));

        txtAreaKommentar.setColumns(20);
        txtAreaKommentar.setLineWrap(true);
        txtAreaKommentar.setRows(5);
        jScrollPane2.setViewportView(txtAreaKommentar);

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        lblSkapaInsProfil.setForeground(new java.awt.Color(0, 0, 255));
        lblSkapaInsProfil.setText("Skapa/ändra profil");
        lblSkapaInsProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSkapaInsProfilMouseClicked(evt);
            }
        });

        cmbKundnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKundnamnActionPerformed(evt);
            }
        });

        jLabel19.setText("1250");

        btnCreateInsamling.setText("Skapa");
        btnCreateInsamling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInsamlingActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(JlistDomanNamn);

        jLabel20.setText("Insamlingsdomäner:");

        lblAddDoman.setForeground(new java.awt.Color(0, 0, 255));
        lblAddDoman.setText("Lägg till domän");
        lblAddDoman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddDomanMouseClicked(evt);
            }
        });
        lblAddDoman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblAddDomanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(230, 230, 230)
                                .addComponent(jLabel11))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbKundnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cmbBoxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbInsamlingsprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(5, 5, 5)
                                            .addComponent(lblSkapaInsProfil))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                .addComponent(txtInsamlingsdoman, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAddDoman)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnCreateInsamling, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel11))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(cmbKundnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtInsamlingsdoman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddDoman))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cmbInsamlingsprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSkapaInsProfil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(cmbBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel20))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnCreateInsamling)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrera Insamling", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 203, 8)));

        jButton3.setBackground(new java.awt.Color(148, 176, 35));
        jButton3.setText("Insamlingsprofil");

        createNewCustomerBtn.setBackground(new java.awt.Color(148, 176, 35));
        createNewCustomerBtn.setText("Skapa Ny Kund");
        createNewCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewCustomerBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Stad:");

        jLabel8.setText("E-mail:");

        jLabel9.setText("Telefon:");

        jLabel10.setText("Namn:");

        jLabel2.setText("Gata:");

        jLabel18.setText("Postkod:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPhoneNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerEmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerStreetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPostCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(createNewCustomerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(customerNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(customerPhoneNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(customerEmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerStreetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(customerPostCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createNewCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrera kund", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initGUIregInsamling(){
      txtDate.setText(getDate());   
      justForDemoPurpose();
    }
    /*private void initJTable() throws SQLException{
        try {    
          //Anropa metod för att lägga till case
            if (insamling.updateJTable().equals("success")){
                JOptionPane.showMessageDialog(this, "Påbörjar initJtable");
                 
            }else{
                JOptionPane.showMessageDialog(this, "Could not create new customer..");
            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
        }    }
        
        */
        public void updateNameCmb() throws SQLException{
        String sRet = "failure";
        Connection cn = null;
        cmbKundnamn.removeAllItems();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");            
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/preservaDB","root","skola");                        
            if (cn == null){
                throw new SQLException("No connection to target database!");
            }
            
            //SQL-statement som skickas till databasen:
            PreparedStatement stmt = cn.prepareStatement("SELECT namn FROM kund");
            //Resultatet från SQL-satsen sparas i ett ResultSet                
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()){
                //Add items to combobox
                cmbKundnamn.addItem(rs.getString("namn"));
            }
        }
        catch (ClassNotFoundException | SQLException ex) {
            throw new SQLException("Problem with db:" + ex.getMessage());
        }
        finally //Stänger anslutningen mot databasen:
        {
            if (cn!=null) 
                cn.close();
        }
    }
    
    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed
    private void cmbKundnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKundnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKundnamnActionPerformed
//Creates a new insamling and updates the mainGUI
    private void btnCreateInsamlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInsamlingActionPerformed
        
        setInsamlingAttribute(insamling);
        //updateGUI(insamling);
        JOptionPane.showMessageDialog(rootPane, "Insamling skapad");
        //Connect to database and add the new customer.
        try {    
          //Anropa metod för att lägga till case
            if (insamling.addInsamling().equals("success")){
            clearInsInputs();
            updateGUI(insamling);
            clearInsInputs();
            }else{
                JOptionPane.showMessageDialog(this, "Could not create new insamling..");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCreateInsamlingActionPerformed

   
    
    public void initJlistDoman() {
        JlistDomanNamn.setModel(listModel);  
        listModel.clear();
        for(int i = 0; i < domannamnArray.size(); i++){
            listModel.addElement(domannamnArray.get(i));
            }
    }
    //Sets insamlingAttribute based on inputs made in register insamling-tab. 
    private void setInsamlingAttribute(InsamlingEntity insamling) {
        insamling.setKundnamn(cmbKundnamn.getSelectedItem().toString()); 
        insamling.setStartDatum(txtDate.getText());
        insamling.setDoman(domannamnArray);
        insamling.setInsamlingsprofil(cmbInsamlingsprofil.getSelectedItem().toString());
        insamling.setStatus(cmbBoxStatus.getSelectedItem().toString());
        insamling.setKommentar(txtAreaKommentar.getText());
        
    }
    private void lblAddDomanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddDomanMouseClicked
        //Adds domains to the list with domain by clicking on label
        String domanNamn = txtInsamlingsdoman.getText();
        if(domanNamn != null){
            domannamnArray.add(domanNamn);
            initJlistDoman();
            
        }else if (domanNamn == null){
            JOptionPane.showMessageDialog(rootPane, "Felaktigt domännamn, vänligen skriv i formen www.example.com");
        }
    }//GEN-LAST:event_lblAddDomanMouseClicked
    private void lblAddDomanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblAddDomanKeyPressed

    }//GEN-LAST:event_lblAddDomanKeyPressed
    private void lblSkapaInsProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSkapaInsProfilMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Skickar användare vidare till verktyg");
    }//GEN-LAST:event_lblSkapaInsProfilMouseClicked
    private void createNewCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewCustomerBtnActionPerformed
        //Create new Customer Entity Class
        CustomerEntity c = new CustomerEntity();
        
        //Get the current number of customers in the database.
        //Then increase that number by one.
        try {
            c.setCustomerNR(c.getNrOfCustomers()+1);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindowUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Get info from textfields and insert into variables.
        c.setName((String)customerNameTxtField.getText());
        c.setPhoneNr((String)customerPhoneNumberTxtField.getText());
        c.setEmail((String)customerEmailTxtField.getText());
        c.setCity((String)customerCityTxtField.getText());
        c.setStreet((String)customerStreetTxtField.getText());
        c.setPostCode((String)customerPostCodeTxtField.getText());
        //c.setOrgNr((String)customerOrgNrTxtField.getText());
        
        //Connect to database and add the new customer.
        try {    
          //Anropa metod för att lägga till case
            if (c.addCustomer().equals("success")){
                JOptionPane.showMessageDialog(this, "New customer added to db!");
                updateNameCmb();  
                clearCustInputs();
            }else{
                JOptionPane.showMessageDialog(this, "Could not create new customer..");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_createNewCustomerBtnActionPerformed
    //Gets todays date
    private String getDate() {
        Calendar currentDate = Calendar.getInstance(); //Hämta nuvarande datum
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy"); //formatera om
        return formatter.format(currentDate.getTime()).toUpperCase();
    }
    //Hard-coded to show how the list will turn out
    private void updateGUI(InsamlingEntity insamling) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        listInsamling.addElement(insamling.toString());
        int data0 = 124;
        String data1 = insamling.getKundnamn();
        String data2 = insamling.getStartDatum();
        String data3 = insamling.getStatus();
        String data4 = "www.preserva.se";
        String data5 = insamling.getKommentar();
        String data6 = "länk";
        String data7 = "länk";
        String data8 = "länk";
        String data9 = "länk";
        
        Object[] row = {data0, data1, data2, data4, data3, data5, data6, data7, data8, data9};
        
        model.insertRow(0, row);
    }
    //Sets attributes, (width, color) to the jTable
    private void setTableAttributes() {
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(22);
     jTable1.getColumnModel().getColumn(5).setPreferredWidth(36);
     jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
     jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
     jTable1.getColumnModel().getColumn(8).setPreferredWidth(40);
     Color green = new Color(148,176,35);
     jTable1.setOpaque(true);
     jTable1.setFillsViewportHeight(true);
     jTable1.setBackground(Color.white);
     JTableHeader header = jTable1.getTableHeader();
     header.setBackground(green);
     jScrollPane4.setBackground(Color.white);
    }
    private void clearCustInputs() {
    customerNameTxtField.setText("");
        customerPhoneNumberTxtField.setText("");
        customerEmailTxtField.setText("");
        customerCityTxtField.setText("");
        customerStreetTxtField.setText("");
        customerPostCodeTxtField.setText("");
        
    }
    private void clearInsInputs(){
        cmbKundnamn.setSelectedIndex(0); 
        txtDate.setText(getDate());
        domannamnArray.removeAll(domannamnArray);
        cmbInsamlingsprofil.setSelectedIndex(0);
        cmbBoxStatus.setSelectedIndex(0);
        txtAreaKommentar.setText("");
    }
    private void justForDemoPurpose() {
        int data0 = 123;
        String data1 = "Preserva";
        String data2 = "26/4/2017";
        String data3 = "Ej startad";
        String data4 = "www.preserva.se";
        String data5 = "Ring Ole innan insamling påbörjar";
        String data6 = "länk";
        String data7 = "länk";
        String data8 = "länk";
        String data9 = "Starta insamling";
        
        Object[] row1 = {data0, data1, data2, data4, data3, data5, data6, data7, data8, data9};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(row1);
        
        data0 = 122;
        data1 = "Regeringenskansliet";
        data2 = "28/4/2017";
        data3 = "Pågår";
        data4 = "www.regeringen.se";
        data5 = "Ingen kommentar..";
        data6 = "länk";
        data7 = "länk";
        data8 = "länk";
        data9 = "länk";
        
        Object[] row2 = {data0, data1, data2, data4, data3, data5, data6, data7, data8, data9};
        model.addRow(row2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindowUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainWindowUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList JlistDomanNamn;
    private javax.swing.JButton btnCreateInsamling;
    private javax.swing.JComboBox cmbBoxStatus;
    private javax.swing.JComboBox cmbInsamlingsprofil;
    private javax.swing.JComboBox cmbKundnamn;
    private javax.swing.JButton createNewCustomerBtn;
    private javax.swing.JTextField customerCityTxtField;
    private javax.swing.JTextField customerEmailTxtField;
    private javax.swing.JTextField customerNameTxtField;
    private javax.swing.JTextField customerPhoneNumberTxtField;
    private javax.swing.JTextField customerPostCodeTxtField;
    private javax.swing.JTextField customerStreetTxtField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddDoman;
    private javax.swing.JLabel lblSkapaInsProfil;
    private javax.swing.JTextArea txtAreaKommentar;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInsamlingsdoman;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
        try{
         insamling.res  = insamling.stat.executeQuery("Select * from insmling");
         while (insamling.res.next()){
             String lopNr = insamling.res.getString(1);
             String kundNamn = insamling.res.getString(2);
             String startDat = insamling.res.getString(3);
             String doman = insamling.res.getString(4);
             String status = insamling.res.getString(5);
             String kommentar = insamling.res.getString(6);
             String url = insamling.res.getString(7);
             Object[] content = {lopNr, kundNamn, startDat, doman, status, kommentar, url};
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.addRow(content);
         }
        }catch (Exception e){
            
        }
    }
    }